package uk.ac.ebi.webservices.chebi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Sun Mar 27 11:13:32 EDT 2011
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", name = "ChebiWebServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ChebiWebServicePortType {

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getStructureSearch", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetStructureSearch")
    @WebMethod
    @ResponseWrapper(localName = "getStructureSearchResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetLiteEntityResponse")
    public uk.ac.ebi.webservices.chebi.LiteEntityList getStructureSearch(
        @WebParam(name = "structure", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.lang.String structure,
        @WebParam(name = "type", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        uk.ac.ebi.webservices.chebi.StructureType type,
        @WebParam(name = "structureSearchCategory", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        uk.ac.ebi.webservices.chebi.StructureSearchCategory structureSearchCategory,
        @WebParam(name = "totalResults", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        int totalResults,
        @WebParam(name = "tanimotoCutoff", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        float tanimotoCutoff
    ) throws ChebiWebServiceFault_Exception;

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getAllOntologyChildrenInPath", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetAllOntologyChildrenInPath")
    @WebMethod
    @ResponseWrapper(localName = "getLiteEntityResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetLiteEntityResponse")
    public uk.ac.ebi.webservices.chebi.LiteEntityList getAllOntologyChildrenInPath(
        @WebParam(name = "chebiId", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.lang.String chebiId,
        @WebParam(name = "relationshipType", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        uk.ac.ebi.webservices.chebi.RelationshipType relationshipType,
        @WebParam(name = "structureOnly", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        boolean structureOnly
    ) throws ChebiWebServiceFault_Exception;

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getOntologyParents", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetOntologyParents")
    @WebMethod
    @ResponseWrapper(localName = "getOntologyParentsResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetOntologyParentsResponse")
    public uk.ac.ebi.webservices.chebi.OntologyDataItemList getOntologyParents(
        @WebParam(name = "chebiId", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.lang.String chebiId
    ) throws ChebiWebServiceFault_Exception;

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getCompleteEntity", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetCompleteEntity")
    @WebMethod
    @ResponseWrapper(localName = "getCompleteEntityResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetCompleteEntityResponse")
    public uk.ac.ebi.webservices.chebi.Entity getCompleteEntity(
        @WebParam(name = "chebiId", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.lang.String chebiId
    ) throws ChebiWebServiceFault_Exception;

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getCompleteEntityByList", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetCompleteEntityByList")
    @WebMethod
    @ResponseWrapper(localName = "getCompleteEntityByListResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetCompleteEntityByListResponse")
    public java.util.List<uk.ac.ebi.webservices.chebi.Entity> getCompleteEntityByList(
        @WebParam(name = "ListOfChEBIIds", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.util.List<java.lang.String> listOfChEBIIds
    ) throws ChebiWebServiceFault_Exception;

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getLiteEntity", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetLiteEntity")
    @WebMethod
    @ResponseWrapper(localName = "getLiteEntityResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetLiteEntityResponse")
    public uk.ac.ebi.webservices.chebi.LiteEntityList getLiteEntity(
        @WebParam(name = "search", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.lang.String search,
        @WebParam(name = "searchCategory", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        uk.ac.ebi.webservices.chebi.SearchCategory searchCategory,
        @WebParam(name = "maximumResults", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        int maximumResults,
        @WebParam(name = "stars", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        uk.ac.ebi.webservices.chebi.StarsCategory stars
    ) throws ChebiWebServiceFault_Exception;

    @WebResult(name = "return", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
    @RequestWrapper(localName = "getOntologyChildren", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetOntologyChildren")
    @WebMethod
    @ResponseWrapper(localName = "getOntologyChildrenResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi", className = "uk.ac.ebi.webservices.chebi.GetOntologyChildrenResponse")
    public uk.ac.ebi.webservices.chebi.OntologyDataItemList getOntologyChildren(
        @WebParam(name = "chebiId", targetNamespace = "http://www.ebi.ac.uk/webservices/chebi")
        java.lang.String chebiId
    ) throws ChebiWebServiceFault_Exception;
}
