
/*
 * 
 */

package uk.ac.ebi.webservices.chebi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Apr 13 10:17:08 EDT 2012
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "ChebiWebServiceService", 
                  wsdlLocation = "http://www.ebi.ac.uk/webservices/chebi/2.0/webservice?wsdl",
                  targetNamespace = "http://www.ebi.ac.uk/webservices/chebi") 
public class ChebiWebServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.ebi.ac.uk/webservices/chebi", "ChebiWebServiceService");
    public final static QName ChebiWebServicePort = new QName("http://www.ebi.ac.uk/webservices/chebi", "ChebiWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://www.ebi.ac.uk/webservices/chebi/2.0/webservice?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://www.ebi.ac.uk/webservices/chebi/2.0/webservice?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ChebiWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ChebiWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChebiWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ChebiWebServicePortType
     */
    @WebEndpoint(name = "ChebiWebServicePort")
    public ChebiWebServicePortType getChebiWebServicePort() {
        return super.getPort(ChebiWebServicePort, ChebiWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChebiWebServicePortType
     */
    @WebEndpoint(name = "ChebiWebServicePort")
    public ChebiWebServicePortType getChebiWebServicePort(WebServiceFeature... features) {
        return super.getPort(ChebiWebServicePort, ChebiWebServicePortType.class, features);
    }

}
